import os
import json
import torch
import torch.nn.functional as F

# Try importing torch_geometric. If missing, print a helpful message but don't crash.
try:
    from torch_geometric.data import Data, DataLoader
    from torch_geometric.nn import GATConv, global_mean_pool
    PYG_AVAILABLE = True
except ImportError:
    PYG_AVAILABLE = False
    print("⚠️ PyTorch Geometric is not installed. To train the GNN, run: pip install torch-geometric")


class TruthLensGAT(torch.nn.Module):
    """
    Graph Attention Network (GAT) for Truth Score prediction.
    Learns to dynamically weight evidence nodes and source nodes relative to the claim.
    """
    def __init__(self, in_channels=16, hidden_channels=32, out_channels=1, heads=4):
        super(TruthLensGAT, self).__init__()
        # PyTorch Geometric GAT layers
        if not PYG_AVAILABLE:
            return
            
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads, dropout=0.2)
        # On the second layer, we set heads=1 or average them to get the final node embeddings
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1, concat=False, dropout=0.2)
        
        # Final classification layer
        self.fc = torch.nn.Linear(hidden_channels, out_channels)

    def forward(self, x, edge_index, batch):
        """
        x: Node feature matrix
        edge_index: Graph connectivity matrix
        batch: Batch vector mapping each node to its respective graph
        """
        if not PYG_AVAILABLE:
            raise RuntimeError("PyTorch Geometric is required for the forward pass.")
            
        x = F.dropout(x, p=0.2, training=self.training)
        x = self.conv1(x, edge_index)
        x = F.elu(x)
        
        x = F.dropout(x, p=0.2, training=self.training)
        x = self.conv2(x, edge_index)
        x = F.elu(x)
        
        # Pool all node embeddings in the graph into a single graph embedding
        # This represents the holistic "Truth state" of the entire evidence graph
        x_graph = global_mean_pool(x, batch)
        
        # Predict the Trust Score (0.0 to 1.0)
        out = torch.sigmoid(self.fc(x_graph))
        return out


def load_gnn_dataset(dataset_dir="dataset/gnn_training"):
    """
    Reads the serialized NetworkX JSON graphs generated by engines/evidence.py
    and converts them into PyTorch Geometric Data objects.
    """
    if not PYG_AVAILABLE:
        print("Cannot load dataset without torch-geometric.")
        return []
        
    if not os.path.exists(dataset_dir):
        print(f"Dataset directory '{dataset_dir}' not found.")
        return []
        
    dataset = []
    
    # Simple feature mapping for v1
    # [is_claim, is_evidence, is_source, semantic_weight, credibility_weight]
    # For a real system, you would plug your MiniLM embeddings directly into these node features!
    feature_dim = 16 
    
    for filename in os.listdir(dataset_dir):
        if not filename.endswith(".json"): continue
        
        filepath = os.path.join(dataset_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            data_dict = json.load(f)
            
        # Parse the NetworkX node-link format
        nodes = data_dict.get("nodes", [])
        links = data_dict.get("links", [])
        
        if not nodes: continue
        
        # 1. Create Node Feature Matrix (x)
        # We dummy-initialize features. In reality, use NLP embeddings for the text.
        x = torch.zeros((len(nodes), feature_dim), dtype=torch.float)
        
        node_id_to_idx = {}
        for i, node in enumerate(nodes):
            node_id_to_idx[node["id"]] = i
            ntype = node.get("type", "unknown")
            if ntype == "claim": x[i, 0] = 1.0
            elif ntype == "evidence": x[i, 1] = 1.0
            elif ntype == "source": x[i, 2] = 1.0
            
        # 2. Create Edge Index
        edge_sources = []
        edge_targets = []
        for link in links:
            src = link.get("source")
            tgt = link.get("target")
            if src in node_id_to_idx and tgt in node_id_to_idx:
                edge_sources.append(node_id_to_idx[src])
                edge_targets.append(node_id_to_idx[tgt])
                
        edge_index = torch.tensor([edge_sources, edge_targets], dtype=torch.long)
        
        # 3. Create Label (y) from the baseline TrustScore
        label = data_dict.get("baseline_trust_score", 0.5)
        y = torch.tensor([[label]], dtype=torch.float)
        
        # Construct PyTorch Geometric Data object
        graph_data = Data(x=x, edge_index=edge_index, y=y)
        dataset.append(graph_data)
        
    print(f"Loaded {len(dataset)} graphs for GNN training.")
    return dataset


def train_gnn_model(epochs=50, lr=0.005):
    """
    Main entry point for training the Graph Attention Network on collected evidence graphs.
    """
    if not PYG_AVAILABLE:
        print("⚠️ Training aborted. PyTorch Geometric not installed.")
        return
        
    dataset = load_gnn_dataset()
    if len(dataset) < 10:
        print("Not enough data to train. Let TruthLens run on Autopilot to collect more graphs!")
        return
        
    loader = DataLoader(dataset, batch_size=4, shuffle=True)
    
    # Initialize Model, Loss, Optimizer
    model = TruthLensGAT()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    criterion = torch.nn.MSELoss() # Mean Squared Error for regression (Trust Score 0-1)
    
    print("🚀 Starting GAT Training on Evidence Graphs...")
    model.train()
    
    for epoch in range(epochs):
        total_loss = 0
        for batch in loader:
            optimizer.zero_grad()
            out = model(batch.x, batch.edge_index, batch.batch)
            loss = criterion(out, batch.y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
        avg_loss = total_loss / len(loader)
        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1:03d}/{epochs} | Loss: {avg_loss:.4f}")
            
    print("✅ Training complete. Saving model to truthlens_gat.pt")
    torch.save(model.state_dict(), "truthlens_gat.pt")

if __name__ == "__main__":
    train_gnn_model()
